spring.application.name=futbol-apirest-norelacional

server.port=8115

# MongoDB Atlas (la base se llama futbol_db y se crea sola al guardar el primer dato)
spring.mongodb.uri=mongodb+srv://usuario:uts2020@johanortiz.psvtbe5.mongodb.net/futbol_db?appName=JohanOrtiz

# Ver los cambios de las plantillas sin reiniciar
spring.thymeleaf.cache=false